Repository pagopa/pagopa-aca-service, pull requests merged in 2023-06, with the labels that each got.

#26 feat: add check pr github action
  .github/auto_assign.yml
  .github/workflows/check_pr.yml
Labels: size/small

#27 CHK-1611-api-key-for-test
  .devops/azure-templates/api-tests.yml
  .devops/deploy-pipelines.yml
  api-tests/ACA-api.tests.json
  api-tests/env/ACA_dev_env.json
  api-tests/env/ACA_uat_blue_env.json
  api-tests/env/ACA_uat_env.json
Labels: size/small

#29 feat(develop): Added client for execute GPD call
  .env.example
  build.gradle.kts
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/aca/client/CreditorInstitutionClient.kt
  src/main/kotlin/it/pagopa/aca/client/GpdClient.kt
  src/main/kotlin/it/pagopa/aca/config/WebClientConfig.kt
  src/main/kotlin/it/pagopa/aca/exceptions/GpdException.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/aca/AcaTestUtils.kt
  src/test/kotlin/it/pagopa/aca/TestUtils.kt
  src/test/kotlin/it/pagopa/aca/client/CreditorInstitutionClientTest.kt
  src/test/kotlin/it/pagopa/aca/client/GdpClientTest.kt
  src/test/kotlin/it/pagopa/aca/config/WebClientConfigTest.kt
  src/test/resources/application.properties
Labels: size/large

#31 Api config api update
  .env.example
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/resources/application.properties
Labels: size/small

#33 fix: add env variables to README + fix docker compose
  README.md
  docker-compose.yml
Labels: size/small

#32 Feat(client) added invalidate method into client
  build.gradle.kts
  src/main/kotlin/it/pagopa/aca/client/GpdClient.kt
  src/main/kotlin/it/pagopa/aca/config/WebClientConfig.kt
  src/test/kotlin/it/pagopa/aca/client/GdpClientTest.kt
  src/test/kotlin/it/pagopa/aca/config/WebClientConfigTest.kt
Labels: size/small

#36 feat(mock): add api-config json server mock
  docker-compose.yml
  mock/json-server/api-config/.gitignore
  mock/json-server/api-config/Dockerfile.api-config-mock
  mock/json-server/api-config/README.md
  mock/json-server/api-config/package.json
  mock/json-server/api-config/src/db.json
  mock/json-server/api-config/src/middleware.js
  mock/json-server/api-config/src/routes.json
  mock/json-server/api-config/yarn.lock
Labels: size/large

#35 feat(logging): format log in ECS json format with logback encoder
  Dockerfile
  build.gradle.kts
  gradle.lockfile
  gradle.properties
  gradle/verification-metadata.xml
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: size/small

#37 Chk 1660 gpd mock
  docker-compose.yml
  mock/json-server/api-config/README.md
  mock/json-server/gpd/.gitignore
  mock/json-server/gpd/Dockerfile.gpd-mock
  mock/json-server/gpd/README.md
  mock/json-server/gpd/package.json
  mock/json-server/gpd/src/db.json
  mock/json-server/gpd/src/middleware.js
  mock/json-server/gpd/src/routes.json
  mock/json-server/gpd/yarn.lock
Labels: size/large

#42 feat(mock): add mock for creation flow
  mock/json-server/api-config/README.md
  mock/json-server/api-config/src/db.json
  mock/json-server/api-config/src/middleware.js
  mock/json-server/gpd/README.md
  mock/json-server/gpd/src/db.json
  mock/json-server/gpd/src/middleware.js
Labels: size/large

#43 feat(mock): fix tests
  mock/json-server/gpd/README.md
  mock/json-server/gpd/src/db.json
  mock/json-server/gpd/src/routes.json
Labels: size/large

#34 feat(post implementation) implemented ACA [POST] /paCreatePosition
  .devops/code-review-pipelines.yml
  .env.example
  api-tests/ACA-api.tests.localhost.json
  api-tests/env/ACA_localhost_env.json
  docker-compose.yml
  mock/json-server/gpd/src/db.json
  src/main/kotlin/it/pagopa/aca/client/GpdClient.kt
  src/main/kotlin/it/pagopa/aca/client/IbansClient.kt
  src/main/kotlin/it/pagopa/aca/exceptions/GpdPositionNotFoundException.kt
  src/main/kotlin/it/pagopa/aca/services/AcaService.kt
  src/main/kotlin/it/pagopa/aca/utils/AcaUtils.kt
  src/test/kotlin/it/pagopa/aca/AcaTestUtils.kt
  src/test/kotlin/it/pagopa/aca/client/GdpClientTest.kt
  src/test/kotlin/it/pagopa/aca/client/IbansClientTest.kt
  src/test/kotlin/it/pagopa/aca/service/AcaServiceTests.kt
  src/test/kotlin/it/pagopa/aca/utils/AcaUtilsTests.kt
Labels: size/large, request-review

#44 fix(body create and update): added remittanceInformation and organiza…
  src/main/kotlin/it/pagopa/aca/utils/AcaUtils.kt
Labels: size/small

#47 fix(openapi) added constraint validation into api-spec
  api-spec/aca-api.yaml
  api-tests/ACA-api.tests.localhost.json
  api-tests/env/ACA_localhost_env.json
  src/main/kotlin/it/pagopa/aca/client/GpdClient.kt
  src/main/kotlin/it/pagopa/aca/client/IbansClient.kt
  src/main/kotlin/it/pagopa/aca/exceptions/GpdException.kt
  src/test/kotlin/it/pagopa/aca/client/GdpClientTest.kt
  src/test/kotlin/it/pagopa/aca/client/IbansClientTest.kt
Labels: size/small
